<a href="https://colab.research.google.com/github/DesmondTim/DesmondTim/blob/main/My_code_snip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
print("""your are welcome to my quiz""")

score=0
playing = input("Do you want to play?")
if playing != "no":
    print("lets get started")

    ans = input("where is the capital of Nigeria?"). lower()
    if ans == "abuja":
        print("you are right!!!")
        score+=1
    else:
        print("you are wrong")

    ans= input("where is Lautech located").lower()
    if ans== "ogbomosho":
        print("you are right")
        score+=1
    else:
        print("you are wrong!!!")

    ans= input("Full meaning of CPU").lower()
    if ans =="central processing unit":
        print("you are right")
        score+=1
    else:
            print("you are wrong!!!")
    ans=input("Full meaning of RAM").lower()
    if ans == "random access memory":
        print("you are right")
        score+=1

    else:
            print("you are wrong")

    ans= input("the president of Nigeria is").lower()
    if ans == "buhari":
      print("you are right!!!")
      score+=1

    else:
      print("you are wrong!!!")
      print("you've come to the end of this quizz your score is",str(score),'/5')
      print("Thanks for playing")

else:
  print("thanks for playing")
  sys.exit

your are welcome to my quiz
Do you want to play?no
thanks for playing


In [ ]:
num= int(input("enter a number:"))
def collartz(num):
    if num%2==0:
        num=num/2
        print(num)
        collartz(num)
    else:
        num=((3*num)+1)
        print(num)
        collartz(num)
if num!= 1:
    collartz(num)
else:
    print("invalid input")


In [ ]:
my_list=[]
res= int(input("enter your number here"))
for res in range(res):
    a=int(input("enter value"))
    my_list.append(a)
print(my_list)
sum(my_list)

enter your number here4
enter value3
enter value4
enter value5
enter value3
[3, 4, 5, 3]


15

In [ ]:
45
dict = {}
dict ['one'] = "This is one"
dict[2] = "This is two"
tinydict = {'name': 'john','code':6734, 'dept': 'sales'}
print dict['one'] # Prints value for 'one' key
print dict[2] # Prints value for 2 key
print tinydict # Prints complete dictionary
print tinydict.keys() # Prints all the keys
print tinydict.values() # Prints all the values

SyntaxError: ignored

In [ ]:
import time
friends=[ 'desmond', 'timmy', 'bunmi','benjamin', 'gbenga', 'funmilayo']
for name in friends:
        print(name)
        time.sleep(2)
print("done")

desmond
timmy
bunmi
benjamin
gbenga
funmilayo
done


In [ ]:
for i in range (1,11):
    if i % 2==0:
        print(i, 'is even')
    else:
        print(i, "is odd")


1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even


In [ ]:
import random
import sys
import time
timespeed=0.1

def intro():
    for letters in "\t\t\tWelcome\n to number guessing created by Desmond":
        print(letters,end="-")
        time.sleep(timespeed)

def guess(x):
    no_of_guess=0
    guesslimit=3
    out_of_guess= False
    random_num=random.randint(1,x)
    guess=""
while guess != random.num:
        guess= int(input("Guess a number: "))
        no_of_guess+=1
        if no_of_guess<guesslimit:
            if guess<random_num:
                print("sorry,guess again. Too low")
            elif guess> random_num:
                print("Sorry, guess again. Too High")
            if no_of_guess ==2:
                    print("This is your last chance")
        elif no_of_guess ==3:
            print("You are out of Guess")
            break
        else:
            print("Hurray!!!, You guessed correctly")
def tryagain():
    res=input("Do you want to tryagain? ").lower()
    if res =="yes":
        intro()
        guess(10)
    else:
        sys.exit


intro()
guess(10)
tryagain()

In [ ]:
import random
def my_comp(x):
  low=1
  high=x
  feedback= ""
  while feedback!="c":
    if low!=high:
      guess=random.randint(low,high)
    else:
      low=high
    feedback= input(f"Enter H if {guess} is high,L if {guess} is low,c if {guess} is correct").lower()
    if feedback =="h":
      high= guess-1
    elif feedback =="l":
      low = guess + 1
  else:
    print(f"Computer has guessed your secret number{guess} correctly")
my_comp(20)


In [ ]:
import random
def my_comp(x):
  low=1
  high=x
  feedback= ""
  while feedback!="c":
    if low!=high:
      guess=random.randint(low,high)
    else:
      low=high
    feedback= input(f"Enter H if {guess} is high,L if {guess} is low,c if {guess} is correct").lower()
    if feedback =="h":
      high= guess-1
    elif feedback =="l":
      low = guess + 1
  else:
    print(f"Computer has guessed your secret number{guess} correctly")
my_comp(20)


In [ ]:
#Functions
#are collection of codes and instruction
def function1():
  print("column")
  print("row")
print("this is outside the function")

this is outside the function


In [ ]:
#calling of function
function1()

column
row


In [ ]:
# can be use as a mapping
def function2(x):
  return 2*x

In [ ]:
 a = function2(3)
#return value or output

In [ ]:
print(a)

6


In [ ]:
b = function2(4)

In [ ]:
print(b)

8


In [ ]:
def function3(x,y):
  return x + y

In [ ]:
#its possible to have many argument in function
e = function3(1,2)
print(e)

3


In [ ]:
def function4(x):
  print(x)
  print("still in this function")
  return 3*x

In [ ]:
f = function4(4)

4
still in this function


In [ ]:
print(f)

12


In [ ]:
def function5(some_argument):
  print(some_argument)
  print("weee")

In [ ]:
function5(4)

4
weee


In [ ]:
#BMI calculator
name1 = "Yk"  #hypothetic person
height_m1= 2
weight_kg1 = 90

name2 = "YK's sister"
height_m2 = 1.8
weight_kg2 = 70

name3 = "YK's brother"
height_m3 = 2.5
weight_kg3 = 160



In [ ]:
def bmi_calculator(name, height_m, weight_kg):
  bmi = weight_kg / (height_m**2)
  print("bmi: ")
  print(bmi)
  if bmi < 25:
    return name + " is not overweight"
  else:
    return name + " is overweight"


In [ ]:
result1 = bmi_calculator (name1, height_m1, weight_kg1)
result2 = bmi_calculator (name2, height_m2, weight_kg2)
result3 = bmi_calculator (name3, height_m3, weight_kg3)

bmi: 
22.5
bmi: 
21.604938271604937
bmi: 
25.6


In [ ]:
print(result1)
print(result2)
print(result3)

Yk is not overweight
YK's sister is not overweight
YK's brother is overweight


In [ ]:

import sys
import random
print("Your'e welcome to my quizz")

print("Press 1 for User guess game and 2 for computer guess game")
res=input("Enter here:")
if res == "1":


 def my_guess(x):
  no_of_guess=0
  guess_limit =3
  out_of_guess =False
  random_num = random.randint(1,x)
  guess= ""
  while guess != random.num:
    guess= int(input("Guess a number: "))
    no_of_guess =1
    if no_of_guess< guess_limit:
      if guess<random_num:
        print("Sorry,guess again. Too Low")
      elif guess> random.num:
        print("Sorry, guess again. Too High")
      if no_of_guess ==2:
        print("This is your last chance")
    elif no_of_guess ==3:
        print("Your'e out of Guess")
        break
    else:
        print("Hurray!!!, You guessed correctly")

elif res=="2":

 def my_comp(x):
  low=1
  high=x
  feedback = ""
  while feedback!="c":
    if low!=high:
      guess=random.randint(low,high)
    else:
      low=high
    feedback= input(f"Enter H if {guess} is high,L if {guess} is low,c if {guess} is correct").lower()
    if feedback =="h":
      high= guess-1
    elif feedback =="l":
      low = guess + 1
  else:
    print(f"Computer has guessed your secret number{guess} correctly")
 my_comp(20)

def tryagain():
  res= input("Do you want to tryagain? ").lower()
  if res =="yes":
    intro()
    guess(10)
  else:
    sys.exist


Your'e welcome to my quizz
Press 1 for User guess game and 2 for computer guess game
Enter here:2
Enter H if 16 is high,L if 16 is low,c if 16 is correcth
Enter H if 3 is high,L if 3 is low,c if 3 is correctl
Enter H if 4 is high,L if 4 is low,c if 4 is correctl
Enter H if 14 is high,L if 14 is low,c if 14 is correctc
Computer has guessed your secret number14 correctly


In [ ]:
 def main(name):
   print("my name is", name)
main("Desmond")

my name is Desmond


In [ ]:
def loop(startnum,endnum):

  if startnum <= endnum:
    print(startnum)
    startnum +=1
    loop(startnum,endnum)
loop(1,10)

1
2
3
4
5
6
7
8
9
10


c

In [ ]:
 alphabets[:4]

'ABCD'

In [ ]:
print("""
**************************
      Welcome to simple Interest App
      Press 1 to solve Interest
      press 2 to solve principal
      Press 3 to solve rate
      press 4 to solve for time
***************************
 """)
def interest(princial,rate,time):
  answer = (principal*rate*time)/100
  print('The simple interest is', answer)
resp = int(input('Enter your choice: '))
while resp not in [1,2,3,4]:
  print('Enter a valid choice: ')
if resp == 1:
  principal =float(input('enter your principal: '))
  rate= float(input('enter your rate: '))
  time= float(input('enter your time'))
  interest(principal,rate,time)
elif resp == 2:
    rate=float(input('enter your rate: '))
    time=float(input('enter your time: '))
    interest(rate,time)
elif resp == 3:
  principal=float(input('enter your principal: '))
  time= float(input('enter your time: '))
  interest(principal,time)
elif resp == 4:
  principal=float(input('enter your principal: '))
  rate=float(input('enter your rate: '))
  interest(principal,rate)

In [ ]:
alphabets[:-5:-1]

'ZYXW'

In [ ]:
N

In [ ]:
a ="Hello-world"
a.splits('-')

In [ ]:
def myfunc(a=0,b="",c=0):
  print("a:",a)
  print("b:",b)
  print("c:",c)

In [ ]:
myfunc("Des","Tim",)

a: Des
b: Tim
c: 0


In [ ]:
myfunc()

a: 0
b: 
c: 0


In [ ]:
def printinfo(*var):
  print("var:", var)

In [ ]:
printinfo(10)

var: (10,)


In [ ]:
printinfo(10,20,30,40)

var: (10, 20, 30, 40)


In [ ]:
def welcome():
  print("You are welcome to Cephas Technologies")
  print("I have gained alot from coming here everyday")
  print("I am looking forward to learn more")
welcome()

You are welcome to Cephas Technologies
I have gained alot from coming here everyday
I am looking forward to learn more


In [ ]:
def addition(a,b):
  c=a+b
  return c
addition(6,5)

11

In [ ]:
import time
def des():
  for i in "DESMOND TIMMY'S ACADEMY":
    print(i,end="")
    time.sleep(0.2)
des()

DESMOND TIMMY'S ACADEMY

In [ ]:
def add (arg1, arg2):

  total = arg1 + arg2

  return total


In [ ]:
add(10,20)
a= add(10,20)
print("outside the function: ",a)

outside the function:  30


In [ ]:
def calculator(val1, val2):

  add=val1+val2
  sub= val1-val2
  mult=val1*val2
  div=val1/val2

  return add,sub,mult,div

In [ ]:
import sys
import time

def homepage():
  for i in """Welcome\n to  DESMOND's CALCULATOR\n1,Quadratic Equation\n2.Simultaneous Equation""":
    print(i,end="")
    time.sleep(0.1)
  res=input("Enter here:")
  if res=="1":
    quadratic()
  elif res=="2":
    simultaneous()
  else :
    print("invalid response")
    homepage()


def quadratic():
  print("SOLVE QUADRATIC")
  a=float(input("Enter value for A"))
  b=float(input("Enter value for B"))
  c=float(input("Enter Value for C"))
  d=(b**2)-(4*a*c)
  x1=(-b+d**0.5)/(2*a)
  x2=(-b-d**0.5)/(2*a)
  print('x1:',x1)
  print('x2:',x2)


def simultaneous():
  print("SOLVE SIMULTANEOUS")
  a1=float(input("Enter value for A1 : "))
  b1=float(input("Enter value for B1 : "))
  c1=float(input("Enter value for C1 : "))
  a2=float(input("Enter value for A2 : "))
  b2=float(input("Enter value for B2 : "))
  c2=float(input("Enter value for C2 : "))
  numx = b2*c1 - b1*c2
  denx = a1*b2 - a2*b2
  numy = a2*c1 - a1*c2
  deny = a2*b1* - a1*b2
  while denx ==0 or deny ==0:
    print("error")
    print("Tryagain")
    simultaneous()
  x = numx/denx
  y = numy/deny
  print("x1 :", x)
  print("y1 :",y)
homepage()

Welcome
 to  DESMOND's CALCULATOR
1,Quadratic Equation
2.Simultaneous EquationEnter here:1
SOLVE QUADRATIC
Enter value for A2
Enter value for B5
Enter Value for C8
x1: (-1.25+1.5612494995995996j)
x2: (-1.25-1.5612494995995996j)


In [ ]:
import sys
import time
def startapp():
  print('''":grinning_face_with_big_eyes":Welcome to GP and AP solver":winking_face_with_tongue":\n
  Enter 1 for AP \U0001F606
  Enter 2 for the sum of an Ap \U0001F923
  Enter 3 for Gp\U0001f600
  Enter 4 for the sum of Gp\N{grinning face}
  Enter q to quit
  ''')
  time.sleep(0.2)


  global operation
  res = input()
  operation=res
  if res =="1":
    result= AP()
    print("The ans is = ", result)

  elif res == "2":
    result= sum_AP()
    print("The sum_Ap ",result)

  elif res == "3":
    result= GP()
    print("The ans is = ", result)

  elif res=="4":
    result= sum_GP()
    print("The sum_GP ", result)
    tryAgain()

  elif res=="q":
    print('Are you sure you want to exit:"y/n"')
    ans= input()
    if ans == "y":
      print("thanks and have a nice day\U0001f600")
      sys.exit
  else:
    startapp()
def AP():
  a=float(input("Enter first term value "))
  n= float(input("Enter the last term value "))
  d= float(input("Enter the common difference value here "))
  T= a+(n-1)*d
  return T

def sum_AP():
  a=float(input("Enter first term value "))
  n= float(input("Enter the last term value "))
  d= float(input("Enter the common difference value here "))
  D= (n-1)*d
  S=n/2 *(2*a + D)
  return S

def GP():
  a= float(input("Enter first term value "))
  n= float(input("Enter the last term value  "))
  r= float(input("Enter the common ratio  "))
  p= (n-1)
  T= a*r**p
  return T

def sum_GP():
  a= float(input("Enter first term value "))
  n= float(input("Enter the last term value  "))
  r= float(input("Enter the common ratio  "))
  if r>1:
    d=(r**n -1)
    e=(r-1)
    S=a*d/e
    return S

def tryAgain():
  print("Do you want to tryAgain?")
  res=input("Enter 'Yes' or 'No' ").lower()
  if res == "yes":
     startapp()

  else:
    sys.exit

startapp()
tryAgain()

":grinning_face_with_big_eyes":Welcome to GP and AP solver":winking_face_with_tongue":

  Enter 1 for AP 😆
  Enter 2 for the sum of an Ap 🤣
  Enter 3 for Gp😀
  Enter 4 for the sum of Gp😀
  Enter q to quit
  


In [ ]:
# import emoji module
import emoji


print(emoji.emojize(":grinning_face_with_big_eyes:"))
print(emoji.emojize(":winking_face_with_tongue:"))
print(emoji.emojize(":zipper-mouth_face:"))


In [ ]:
import math                                          # place imports at the top

def circumference(area):
    circ = (math.sqrt(float(area))) / (math.pi)      #<- cast param to float, use math.sqrt
    return circ                                      #<- return the result

area = input("Please choose an area for your circle: ")
print("The circumference is: ", circumference(area)) #<- call the function with a parameter

Please choose an area for your circle: 5
The circumference is:  0.7117625434171772


In [ ]:
height = float(input("Height of trapezoid: "))
base_1 = float(input('Base one value: '))
base_2 = float(input('Base two value: '))
area = ((base_1 + base_2) / 2) * height
print("Area is:", area)

Height of trapezoid: 3
Base one value: 5
Base two value: 7
Area is: 18.0


In [ ]:
import math

r = float(input("Radius of a Circle: "))

area = math.pi * r ** 2


print (area)

Radius of a Circle: 5
78.53981633974483


In [ ]:
import sys

def mycal():
  print('''Welcome here\n
  press 1 for Cc
  Press 2 for Ac
  Press 3 for At
  Press q to quit
  ''')


  global operation
  res= input()
  operation= res
  if res == "1":
    result= Cc()
    print("The ans is = ", result)

  elif res== "2":
    result= Ac()
    print("The ans is =", result)

  elif res=="3":
    result=At()
    print("The ans is =", result)

  elif res=="q":
    print('Are you sure you want to exit:"y/n"')
    ans= input()
    if ans == "y":
      print("thanks and have a nice day")
      sys.exit
  else:
    mycal()

import math                                          # place imports at the top

def circumference(area):
    circ = (math.sqrt(float(area))) / (math.pi)      #<- cast param to float, use math.sqrt
    return circ                                      #<- return the result

    area = input("Please choose an area for your circle: ")
    print("The circumference is: ", circumference(area)) #<- call the function with a parameter


import math
def Cc():
  r = float(input("Radius of a Circle: "))

  area = math.pi * r ** 2


  print (area)

def At():
  height = float(input("Height of trapezoid: "))
  base_1 = float(input('Base one value: '))
  base_2 = float(input('Base two value: '))
  area = ((base_1 + base_2) / 2) * height
  print("Area is:", area)

def tryAgain():
  print("Do you want to tryAgain?")
  res=input("Enter 'Yes' or 'No' ").lower()
  if res == "yes":
    mycal()
  else:
    sys.exit

mycal()
tryAgain()

Welcome here

  press 1 for Cc
  Press 2 for Ac
  Press 3 for At
  Press q to quit
  
1
Radius of a Circle: 5
78.53981633974483
The ans is =  None
Do you want to tryAgain?
Enter 'Yes' or 'No' yes
Welcome here

  press 1 for Cc
  Press 2 for Ac
  Press 3 for At
  Press q to quit
  
2


NameError: ignored

In [ ]:
import sys

def myfunc():
  for i in  """Desmond calculator\n 1.Circumference of a Circle\n 2.Area of a circle\n 3. Area of a Trapezium""":
    print(i,end= "")
  res=input("enter here: ")
  if res == "1":
    circumference()


  elif res =="2":
    circle()

  elif res =="3":
    trapezium()

  else:
    print("Invalid response")
    myfunc()

import math                                          # place imports at the top

def circumference(area):
    circ = (math.sqrt(float(area))) / (math.pi)      #<- cast param to float, use math.sqrt
    return circ                                      #<- return the result

    area = input("Please choose an area for your circle: ")
    print("The circumference is: ", circumference(area)) #<- call the function with a parameter



import math

def Ac():
  r = float(input("Radius of a Circle: "))

  area = math.pi * r ** 2


  print (area)

def At():
  height = float(input("Height of trapezoid: "))
  base_1 = float(input('Base one value: '))
  base_2 = float(input('Base two value: '))
  area = ((base_1 + base_2) / 2) * height
  print("Area is:", area)

def tryAgain():
  print("Do you want to tryAgain?")
  res=input("Enter 'Yes' or 'No' ").lower()
  if res == "yes":
    mycal()
  else:
    sys.exit

myfunc()
tryAgain()

Desmond calculator
 1.Circumference of a Circle
 2.Area of a circle
 3. Area of a Trapezium

KeyboardInterrupt: ignored

In [ ]:
dict1 = {"Name": "Zara", "Age": 7, "Class": "First"}
dict1["Name"]

'Zara'

In [ ]:
for keys,values in dict1.items():
  print(keys,values)

Name Zara
Age 7
Class First


In [ ]:
file = open("desmond.txt",'x')

In [ ]:
a = {1,2,3,4,5}
b= {3,4,5}

In [ ]:
type(a)

set

In [ ]:
b.issubset(a)

True

In [ ]:
b.intersection_update()

In [ ]:
3

3

In [ ]:
def my_salary():

  salary= float(input("Enter your salary: "))
  years = float(input("Enter your years: "))

if salary  > 100000:

  print("Your percent is 15%")

elif salary  > 50000 and <=100000:

  print("Your percent is 10%")

elif salary is <= 50000:

  print("Your percent is 5%")

elif :
  print(try_Again)
my_salary()

In [ ]:
salary= float(input("Enter amount of salary : "))
years = float(input("Enter years of service : "))

if years < 30:
  if years > 10:
    bonus = salary* 0.1
  elif years >=6:
    bonus =salary* 0.08
  elif years < 6:
    bonus = salary*0.05

else:
  print("You can only work in my company for 30years only")

print(f'You have been working here for {years} years\n Your salary is {salary}\nBonus given: {bonus}')
print("Total salary:",salary+bonus)

Enter amount of salary : 30000
Enter years of service : 12
You have been working here for 12.0 years
 Your salary is 30000.0
Bonus given: 3000.0
Total salary: 33000.0


In [ ]:
word= input("Enter word: ")
word=word[::-1]
print(word)

Enter word: Desmond
dnomseD


In [ ]:
import os
os.system("C:\\Users\\HP\\Music\\Adam_Levine_Locked_Away.mp3")

In [ ]:
def my_salary():
  salary= float(input("Enter amount of salary : "))
  years = float(input("Enter years of service : "))

if years < 30:

  if years > 10:
    bonus = salary* 0.1
  elif years >=6:
    bonus =salary* 0.08
  elif years < 6:
    bonus = salary*0.05

else:
  print("You can only work in my company for 30years only")

print(f'You have been working here for {years} years\n Your salary is {salary}\nBonus given: {bonus}')
print("Total salary:",salary+bonus)

my_salary()

You have been working here for 2.0 years
 Your salary is 100.0
Bonus given: 5.0
Total salary: 105.0


In [ ]:
from email.message import EmailMessage
from app2 import password
import ssl
import smtlib

email_sender + "codewithdesmondtimmy2021@gmail.com"
email_password = sgntjanvwalybndi

email_receiver = "lenen68873@dineroa.com"

subject= "Don't for get to subscribe"

body= """
When you watch the video,pls hit subscribe
"""

em = EmailMessage()
em = ['from'] = email_sender
em["To"]= email_receiver
em["Subject"]= subject
em.set_content(body)


context = ssl.create_default_context()

with smtplib.SMTP_SSL("smtp.gmail.com", 456, context = context) as smtp:

  smtp.login(email_sender, email_password)
  smtp.sendmail(email_sender, email_receiver, em.as_string())


In [ ]:
import random

In [ ]:
#print random integers within a specific range of numbers

In [ ]:
random.randint() #the start and stop

In [ ]:
random.random()

0.4176109032022596

In [ ]:
r1= random.randint(1,10)
print(r1)# the start and the stop

1


In [ ]:
#random.randrange doesn't add the last number to the result
a= random.randrange(12,20)
print(a)

14


In [ ]:
e=random.uniform(11,2)
e= round(e,2)
print(e)

7.34


In [ ]:
#randoming through a string

name ="Cephas_digital_tecnology"
letter= random.choice(name)
print(letter)

i


In [ ]:
# working with a list

fruits = ['oranges','pawpaw','guava','watermelon','cashew','mangoe']
numbers = [1,2,3,4,5,6,7,7]
fruit = random.choice(fruits)
number = random.choice(numbers)
print(f"i ate {fruit} in {number} times today")

i ate cashew in 6 times today


In [ ]:
new_fruit= (fruits)
random.shuffle(new_fruit)
print(new_fruit)

['guava', 'pawpaw', 'mangoe', 'oranges', 'watermelon', 'cashew']


In [ ]:
print(new_fruit)

None


In [ ]:
c= [1,2,3,4]
random.shuffle(c)
print(c)

[3, 1, 4, 2]


In [ ]:
import random
import time

def intro():
  global b
  b = """\n WELCOME
  TO MY NUMBER GUESSING GAME"""
  for i in b:
    print(i,end="*")
    time.sleep(0.12)
no_of_guess= 0
guess_limit=3
out_of_guess= False


def guess(x):
  global no_of_guess
  global guess_limit
  global out_of_guess
  guess=""
  random_num = random.randint(1,x)
  while guess != random_num and not out_of_guess:
    guess= int(input("guess a number from 1 to {}". format(x)))
    no_of_guess+=1
    if no_of_guess< guess_limit:
      if guess>random_num:
        print("Sorry, guess is too high\U0001f600")
      elif guess< random_num:
        print("Sorry, guess is too low \U0001f601")

    elif no_of_guess == 3:
      print("You're out of guesses")
      break
  else:
    print(f"Hurray, you have guessed{random_num} correctly")



intro()
guess(20)


* *W*E*L*C*O*M*E* *
* * *T*O* *M*Y* *N*U*M*B*E*R* *G*U*E*S*S*I*N*G* *G*A*M*E*guess a number from 1 to 2011
Sorry, guess is too low 😁
guess a number from 1 to 2016
Sorry, guess is too low 😁
guess a number from 1 to 2018
You're out of guesses


In [ ]:
for i in range (1,20):
    if i % 3==0:
        print(i, 'is prime')
    else:
        print(i, "is not prime")


1 is not prime
2 is not prime
3 is prime
4 is not prime
5 is not prime
6 is prime
7 is not prime
8 is not prime
9 is prime
10 is not prime
11 is not prime
12 is prime
13 is not prime
14 is not prime
15 is prime
16 is not prime
17 is not prime
18 is prime
19 is not prime


In [ ]:
b= input("Enter here your number: ")
for i in b:
  print(i,end= "")
  for i in range (1,20):
    if i % 3==0:
        print(i, 'is prime')
    else:
        print(i, "is not prime")
        break


Enter here your number: 3
31 is not prime


In [ ]:
num= int(input("Enter number here : "))
prime=None
for i in range(3,num+1):
  if num%i ==0:
    num=False
  else:
    num=True
if num:
  print("A prime number")
else:
  print("is not prime number")

In [ ]:
def factorial(n):
  fact= 1
  for i in range(2, n+1):
    fact*=1
    return fact
factorial(15)

In [ ]:
def permute (string,pocket=""):
  if len (string)== 0:
    print(pocket)
  else:
    for i in range (len(string)):
      letter = string[i]
      front = string[0:1]
      back= string[i+1:]
      together= front+back
      permute(together,letter+pocket)

print(permute("ABCD", ""))

In [ ]:
import random
def ML(x):
  low=1
  high=x
  res= ""
  while res!="c":
    if low!=high:
      guess= random.randint(low,high)

    else:
      low=high
      res=input(f"Enter H if {guess} is high, L if {guess} is low, C if {guess} is correct").lower()
      if res=="h":
        guess=-1
      elif res=="l":
        guess=+1

  else:
    print("You have successfully guess the secret number correctly")

ML(200)


In [ ]:
import random
no_of_guess=0
guess_limit =4
out_of_guess =False

words=[" Atelier", "Banquette", "Disincline","Impromptu", "Peignoir","Pirogue", "Plapitant", "Pravus", "Quadroon", "Soiree", "Tragedian",
 "bewilder","Desmond","Timmy","Cephas","Technology","Tech"," cicatrice","conscientia"," compendium"]

b = random.choice(words)
guess= " "
while guess!=out_of_guess:

  guess = input("Guess the secret words: ")

  if no_of_guess ==4:
    print(words[1::2])

    if len(guess)<=5:

       print("Try to remember the words")


  else:
    print("Try harder")
    continue



Try harder
Try harder


In [ ]:


file = open("Words.txt","x")

In [ ]:
import time

In [ ]:
#to get

In [ ]:
import datetime

CLASS


In [ ]:
# A class is a collection of object
# when creating a class we normally use Capital letter and we use class to create a class

In [ ]:
class Myclass:
  x

NameError: ignored

In [ ]:
Numpy

In [ ]:
#It is known as nuemrical python
# its a foundational package on which many of the most common data science are built
#it provides us with high performance

In [ ]:
import numpy as np


In [ ]:
import numpy as np
an_argentina= np.array([3,33,333])#rank 1 array
an_argentina

array([  3,  33, 333])

In [ ]:
#you can find the type using this type(array variable)

In [ ]:
print(type(an_array))

<class 'numpy.ndarray'>


In [ ]:
x= 4.0
str (x)


'4.0'

In [ ]:
#NUMPY DIMENSION

import numpy as np
a = np.array([[1,2,3],[4,5,6]])# 2 dim of array
a.ndim

2

In [ ]:
a.ndim
#we use this to have acces to element of multi dimension arrays

2

In [ ]:
b= np.array([[[[1,2,3],[4,5,6],[7,8,9],[0,0,0]]]])
b.ndim

In [ ]:
#SHAPE

In [ ]:
c= np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1.-2-3],[-4,-5,-6],[0,0,1]]])

<ipython-input-73-8318afc59234>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c= np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1.-2-3],[-4,-5,-6],[0,0,1]]])


In [ ]:
c.ndim

2

In [ ]:
c.shape

(2, 3)

In [ ]:
d= np.array([[[[2,4,5,],[6,-2,7],[8,-1,-2]]],[[[4,6,8],[10,-4,7],[3,3,-3],[0,0,0]]]])

<ipython-input-54-df24496925d0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d= np.array([[[[2,4,5,],[6,-2,7],[8,-1,-2]]],[[[4,6,8],[10,-4,7],[3,3,-3],[0,0,0]]]])


In [ ]:
d.ndim

2

In [ ]:
d.shape

(2, 1)

In [ ]:
#RAnk means non-zero row


In [ ]:

c = index[[0]]=91
print(c)

NameError: ignored

In [ ]:
f= np.array([[1,2,3],[3,4,6]])

In [ ]:
f.ndim

2

In [ ]:
f[0]=90
print(f)

In [ ]:
f= np.array([[1,2,3]])

In [ ]:
f[0]= 20
print(f)

In [ ]:
#SORT

In [ ]:
import numpy as np
c= np.array([[[[2,4,5,],[6,-2,7],[8,-1,-2]]],[[[4,6,8],[10,-4,7],[3,3,-3],[0,0,0]]]])
c.sort()

<ipython-input-90-cc3c63d64d0a>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c= np.array([[[[2,4,5,],[6,-2,7],[8,-1,-2]]],[[[4,6,8],[10,-4,7],[3,3,-3],[0,0,0]]]])


In [ ]:
c.size

2

In [ ]:
c.sort


<function ndarray.sort>

In [ ]:
import numpy as np

In [ ]:
ai=np.zeros((4,4))#print zeros in both rows and coloumn
print(ai)

In [ ]:
ai.np.ones(1,2)# to print 1 throughtout
print(ai)

In [ ]:
ai.eyes(5)#eyes means diagonal

In [ ]:
import numpy as np
tp1 = np.random.random((3,5))
print(tp1)
#create an array random between 0 and 1

[[0.12493867 0.11390345 0.92148679 0.78878629 0.85557802]
 [0.61144464 0.57692017 0.33291088 0.70221893 0.68618129]
 [0.24688347 0.33164319 0.80248975 0.00182766 0.37487625]]


In [ ]:
wo=np.arange(10)
print(wo)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
e= np.arange(6)
a=np.random.permutation(e)
print(a)

[1 0 2 5 4 3]


In [ ]:
s = "Cephas ICT Hub"
print(s[0::2])

Cpa C u


In [ ]:
import numpy as np
an_arrays = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_arrays)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [ ]:
an_arrays[1::2,1::2]

array([[22, 24]])

In [ ]:
an_arrays[2,1:5:2]

array([32, 34])

In [ ]:
an_arrays[1:2,1::2];[2,1:5:2]

In [ ]:
an_arrays[[1,1::2];[2,1:5:2]]








In [ ]:
ex=np.full((4,5),10)
print(ex)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


BOOLEAN INDEXING


In [ ]:
an_array=np.array([[33,65],[41,33],[64,33],])
filter=(an_array<40)
print(filter)

[[ True False]
 [False  True]
 [False  True]]


In [ ]:
an_array[an_array%4==0]+=20
an_array

array([[33, 65],
       [41, 33],
       [84, 33]])

In [ ]:
an_array[an_array%3==0]+=3
an_array

array([[ 53,  65],
       [ 41,  53],
       [104,  53]])

In [ ]:
#random.random is from 0 to 1
#but random.rand generate it anyhow

In [ ]:
arr= np.random.rand(5,7)
print(arr)

[[0.68358136 0.34600701 0.17309029 0.00690731 0.2467699  0.14177162
  0.7102947 ]
 [0.17826618 0.38194488 0.89878203 0.19661199 0.56620785 0.89749221
  0.10692893]
 [0.84786196 0.20735155 0.98201953 0.06249663 0.62293421 0.22863524
  0.85832222]
 [0.72058647 0.02165108 0.85492747 0.75861671 0.06648478 0.60142054
  0.93948021]
 [0.06743376 0.95267102 0.73902935 0.67852017 0.67191848 0.13994229
  0.43701434]]


In [ ]:
#to find mean
print(arr.mean())

0.4855421216728712


In [ ]:
print(arr.ave())

In [ ]:
#let find the mean by row
print(arr.mean(axis=1))

[0.3297746  0.46089058 0.54423162 0.56616675 0.52664706]


In [ ]:
#let find for coloumn
print(arr.mean(axis=0))

[0.49954594 0.38192511 0.72956974 0.34063056 0.43486304 0.40185238
 0.61040808]


In [ ]:
#let find the sum of all the element
print(arr.sum())

16.99397425855049


In [ ]:
#let find the median
print(np.median(arr,axis=1))

[0.2467699  0.38194488 0.62293421 0.72058647 0.67191848]


In [ ]:
#sum of row
print(arr.sum(axis=1))

[2.30842219 3.22623407 3.80962133 3.96316726 3.68652941]


In [ ]:
#sum of all coloumn
print(arr.sum(axis=0))

[2.49772972 1.90962554 3.64784868 1.70315281 2.17431521 2.00926189
 3.0520404 ]


In [ ]:
#SORT

In [ ]:
unsorted=np.random.randn(6)
print(unsorted)

[-0.5964281   0.76369413  0.43290858  1.49581308  0.37450841  0.39049321]


In [ ]:
unsorted.sort()
print(unsorted)

[-0.5964281   0.37450841  0.39049321  0.43290858  0.76369413  1.49581308]


In [ ]:
#Unique Element
# unique element are element that appears exactly once in array

In [ ]:
arr= np.array([1,1,2,1,4,3,3,5,6,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [ ]:
#Set Operations
set1= np.array(["Amala","Puff-Puff","Onion"])
set2= np.array(["Pine","Guava","Orange"])
print(set1,set2)

['Amala' 'Puff-Puff' 'Onion'] ['Pine' 'Guava' 'Orange']


In [ ]:
print(np.intersect1d(set1,set2))# intersect means what's common between them
#it printed empty set because there is nothing common between them

[]


In [ ]:
print(np.union1d(set1,set2))

['Amala' 'Guava' 'Onion' 'Orange' 'Pine' 'Puff-Puff']


In [ ]:
print(np.setdiff1d(set1,set2))# what's in set1 and not in set2

['Amala' 'Onion' 'Puff-Puff']


In [ ]:
#in
print(np.in1d(set1,set2))#element thats in set1 thats also in set2

[False False False]


In [ ]:
print(np.setdiff1d(set2,set1))#whats in set2 and not in set1

['Guava' 'Orange' 'Pine']


In [ ]:
#Transpose of matrix
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
bab=arr.T #you can use another variable, thats why i used Bab
bab


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#Indexing using where
x_1=np.array([1,2,3,4])
y_2=np.array([10,11,12,13,14,15])
filter=np.array([True,False,True,False,True,True])

In [ ]:
mat = np.random.rand(5,5)
mat

array([[0.2638324 , 0.90421675, 0.18333078, 0.03907126, 0.57487984],
       [0.85045638, 0.54485228, 0.61537449, 0.33463491, 0.27244276],
       [0.3225906 , 0.90562443, 0.11415373, 0.7312909 , 0.32335097],
       [0.20812703, 0.30784226, 0.67539609, 0.35316052, 0.03522649],
       [0.10480762, 0.16700799, 0.20586848, 0.88530196, 0.32351018]])

In [ ]:
np.where(mat>0.5,1000,-1)#(0.5)any element greater than 0.5,change it to 1000,else change it to -1

array([[  -1, 1000,   -1,   -1, 1000],
       [1000, 1000, 1000,   -1,   -1],
       [  -1, 1000,   -1, 1000,   -1],
       [  -1,   -1, 1000,   -1,   -1],
       [  -1,   -1,   -1, 1000,   -1]])

In [ ]:
#Dot product on matrices and Inner Product on Vectors
x2d= np.array([[1,1],[1,1]])
y2d= np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [ ]:
x2d*y2d

array([[2, 2],
       [2, 2]])

In [ ]:
x2d

y2d

array([[2, 2],
       [2, 2]])

In [ ]:
#determine the inner product of two vectors
v1d=np.array([5,5])
f1d=np.array([6,7])

print(v1d.dot(f1d))
print()
print(np.dot(v1d,f1d))

65

65


In [ ]:
v1d=np.array([5,5])
f1d=np.array([6,7])

print(f1d.dot(v1d))
print()# for space
print(np.dot(v1d,f1d))

65

65


In [ ]:
#dot produce on an array and vector
print(x2d.dot(v1d))
print()
print(np.dot(x2d,v1d))

[10 10]

[10 10]


SUM

---



---



In [ ]:
#sum elements in array
ex1=np.array([[11,12],[21,23]])

print([np.sum(ex1)])

[67]


In [ ]:
print(ex1.sum(axis=0))#coloumn sum
print()
print(ex1.sum(axis=1))#row sum

[32 35]

[23 44]


In [ ]:
#random array
x=np.random.randn(9)
x
print()
y=np.random.rand(9)
y

array([0.46781431, 0.19453865, 0.1743213 , 0.97609191, 0.40600727,
       0.8126249 , 0.33349435, 0.13552051, 0.28601138])

In [ ]:
np.maximum(x,y)

array([0.46781431, 0.19453865, 0.1743213 , 0.97609191, 0.58734617,
       0.8126249 , 0.33349435, 0.13552051, 0.55445174])

RE-SHAPING ARRAY

In [ ]:
#grab a value from 0 to 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#reshape to be a 4x5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#transpose
ex1=np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

In [ ]:
#Indexing using where()

x_1 = np.array([1,2,3,4,5,6])

y_1 = np.array([11,22,33,44,55,66])

filter=np.array([True,False,True,False,True,False])

In [ ]:
out= np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5 66]


In [ ]:
mat= np.random.rand(5,6)
mat

array([[0.01446867, 0.75134183, 0.53918401, 0.93523666, 0.91670617,
        0.17377303],
       [0.73466244, 0.09210237, 0.72449374, 0.5034382 , 0.46159759,
        0.4774967 ],
       [0.56111923, 0.74573745, 0.52316056, 0.26899828, 0.95371645,
        0.33841344],
       [0.89581969, 0.98463452, 0.93217095, 0.06155797, 0.37237583,
        0.95360315],
       [0.0475463 , 0.90766187, 0.12580118, 0.56274067, 0.2510447 ,
        0.07762393]])

In [ ]:
np.where(mat>0.5,1000,-1)

array([[  -1, 1000, 1000, 1000, 1000,   -1],
       [1000,   -1, 1000, 1000,   -1,   -1],
       [1000, 1000, 1000,   -1, 1000,   -1],
       [1000, 1000, 1000,   -1,   -1, 1000],
       [  -1, 1000,   -1, 1000,   -1,   -1]])

In [ ]:
arr_bools=np.array([True,False,True,True,False])


In [ ]:
arr_bools.any()

True

In [ ]:
arr_bools.all()

In [ ]:
def get_drug_description(condition):
    if condition == "malaria":
        return "Drug X is an antimalarial medication commonly used for treating malaria. It works by killing the malaria parasites in the body and preventing further infection."
    elif condition == "cough":
        return "Drug Y is a cough suppressant that helps relieve cough symptoms. It works by reducing the urge to cough and soothing the throat."
    elif condition == "catarrh":
        return "Drug Z is an over-the-counter medication used for relieving symptoms of catarrh, such as nasal congestion and runny nose. It helps reduce inflammation and congestion in the nasal passages."
    else:
        return "Sorry, we don't have a drug description for that condition."

# Example usage:
condition = input("Enter a condition (malaria, cough, catarrh): ")
description = get_drug_description(condition.lower())
print(description)


Enter a condition (malaria, cough, catarrh): 1


In [ ]:
import sys
import time

def homepage():
  for i in """Welcome\n to  DESMOND's CALCULATOR\n1,Quadratic Equation\n2.Simultaneous Equation""":
    print(i,end="")
    time.sleep(0.1)
  res=input("Enter here:")
  if res=="1":
    quadratic()
  elif res=="2":
    simultaneous()
  else :
    print("invalid response")
    homepage()


def quadratic():
  print("SOLVE QUADRATIC")
  a=float(input("Enter value for A"))
  b=float(input("Enter value for B"))
  c=float(input("Enter Value for C"))
  d=(b**2)-(4*a*c)
  x1=(-b+d**0.5)/(2*a)
  x2=(-b-d**0.5)/(2*a)
  print('x1:',x1)
  print('x2:',x2)


def simultaneous():
  print("SOLVE SIMULTANEOUS")
  a1=float(input("Enter value for A1 : "))
  b1=float(input("Enter value for B1 : "))
  c1=float(input("Enter value for C1 : "))
  a2=float(input("Enter value for A2 : "))
  b2=float(input("Enter value for B2 : "))
  c2=float(input("Enter value for C2 : "))
  numx = b2*c1 - b1*c2
  denx = a1*b2 - a2*b2
  numy = a2*c1 - a1*c2
  deny = a2*b1* - a1*b2
  while denx ==0 or deny ==0:
    print("error")
    print("Tryagain")
    simultaneous()
  x = numx/denx
  y = numy/deny
  print("x1 :", x)
  print("y1 :",y)
homepage()

Welcome
 to  DESMOND's CALCULATOR
1,Quadratic Equation
2.Simultaneous EquationSOLVE QUADRATIC


In [ ]:
def drug_des(state):
  for i in """Welcome to Desmond's Store\n1,Malaria\n2,Cough\n3.Catarrh""":
    print(i,end="")
  res=input("enter here: ")
  if res =="1":
    malaria()

  elif res=="2":
    cough()

  elif res=="3":
    catarrh()

  else:
      print("invalid syntax")
      drug_des()


    def malaria():
      res=input("How many days have you been having this Malaria: ")
      if res=="<5 days":
        print("You need to buy malaria drugs")
      else:
        print("Re-read")
        malaria()


drug_des

In [ ]:
#how to access your column in dataset
#variable.column
#to know the number of column and row
#variables.shape
#iloc means index location
#loc means normal location

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive') #then change the slash to backward to stop the code

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
data= pd.read_csv('/content/drive/MyDrive/Dataset/weatherAUS.csv')

In [ ]:
data.head()#to print five first line of data starting fro

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [ ]:
print("hello")

hello


In [ ]:
n= int(input("Enter a number: "))
i=1
while i <=12:
  product= n*i
  print(f"{n} x {i} = {product}")
  i += 1

In [ ]:
print(5/8)

print(7+10)


0.625
17


STARTING ALL OVER AGAIN FROM PYTHON...LORD HELP ME



FILE SYSTEM


In [ ]:
*temporary file
*permanent file

To open file(first method)

In [ ]:
f = open("sample.txt",mode='r')#the default mode is r
print(f)
f.close()

<_io.TextIOWrapper name='sample.txt' mode='r' encoding='UTF-8'>


In [ ]:
f.close()
#once you open you have to close your files

###To open file (second method)

In [ ]:
with open("sample.txt") as f:
  print(f)
  #once you use with open method you dont have to close, it close automatically

<_io.TextIOWrapper name='sample.txt' mode='r' encoding='UTF-8'>


In [ ]:
with open ("sample.txt") as f:
  print([text for text in f])


["'Twas brillig, and the slithy toves\n", 'Did gyre and gimble in the wabe;\n', 'All mimsy were the borogoves,\n', 'And the mome raths outgrabe.\n', '\n', '"Beware the Jabberwock, my son!\n', 'The jaws that bite, the claws that catch!\n', 'Beware the Jubjub bird, and shun\n', 'The frumious Bandersnatch!"\n', '\n', 'He took his vorpal sword in hand:\n', 'Long time the manxome foe he sought,\n', 'So rested he by the Tumtum tree,\n', 'And stood a while in thought.\n', '\n', 'And, as in uffish thought he stood,\n', 'The Jabberwock, with eyes of flame,\n', 'Came whiffling through the tulgey wood,\n', 'And burbled as it came!\n', '\n', 'One two! One two! And through and through\n', 'The vorpal blade went snicker-snack!\n', 'He left it dead, and with its head\n', 'He went galumphing back.\n', '\n', '"And hast thou slain the Jabberwock?\n', 'Come to my arms, my beamish boy!"\n', '"Oh frabjous day! Callooh! Callay!"\n', 'He chortled in his joy.\n', '\n', "'Twas brillig, and the slithy toves\n",

In [ ]:
with open("sample.txt") as f:
  print(f.read())

'Twas brillig, and the slithy toves
Did gyre and gimble in the wabe;
All mimsy were the borogoves,
And the mome raths outgrabe.

"Beware the Jabberwock, my son!
The jaws that bite, the claws that catch!
Beware the Jubjub bird, and shun
The frumious Bandersnatch!"

He took his vorpal sword in hand:
Long time the manxome foe he sought,
So rested he by the Tumtum tree,
And stood a while in thought.

And, as in uffish thought he stood,
The Jabberwock, with eyes of flame,
Came whiffling through the tulgey wood,
And burbled as it came!

One two! One two! And through and through
The vorpal blade went snicker-snack!
He left it dead, and with its head
He went galumphing back.

"And hast thou slain the Jabberwock?
Come to my arms, my beamish boy!"
"Oh frabjous day! Callooh! Callay!"
He chortled in his joy.

'Twas brillig, and the slithy toves
Did gyre and gimble in the wabe:
All mimsy were the borogoves,
And the mome raths outgrabe.



WRITE FILE


In [ ]:
with open("sample.txt") as f:

    print(f.readlines())

[]


In [ ]:
multiplication_table=[]
for i in range(1,13):
  multiplication_table.append(i*2)
print(multiplication_table)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]


In [ ]:


with open("tables.txt", mode="w") as multiplication_table2:
  print(multiplication_table, file=multiplication_table2)

APPEND

In [ ]:
#write
with open("sample.txt",mode="a") as multiplication_table2:# using append to add more to the files in order not to override
  print(multiplication_table, file=multiplication_table2)

WRITE TO CSV FILE


In [ ]:
from csv import writer

platform= "Laptop"
password=1111
pass_data= [platform, password]

with open("tables_csv.csv", mode="w") as f:
 writer_data =writer(f)
 writer_data.writerow(pass_data)

In [ ]:
#### SIMPLE REGISTRATION FORM
#     ACCEPT THE INPUT
name= input("Enter your name: ")
phone_number= input("Enter your phone number: ")
email= input("Enter your email: ")
password= input("Enter your password: ")
confirm_password= input("Confirm your password: ")

#save the above info
details=[name,phone_number,email,password,confirm_password]
with open("student_details1.csv", mode="w") as f:
  writer_data= writer(f)
  writer_data.writerow(details)

In [ ]:
#### SIMPLE REGISTRATION FORM
#     ACCEPT THE INPUT
name= input("Enter your name: ")
phone_number= input("Enter your phone number: ")

password= input("Enter your password: ")


#save the above info
details=[name,phone_number,password,]
with open("student_details2.csv", mode="a") as f:
  writer_data= writer(f)
  writer_data.writerow(details)

Enter your name: desmond
Enter your phone number: 99382266
Enter your password: 23443


In [ ]:
###login form
phone_number= input("Enter your phone number: ")
password= input("Enter your password: ")
with open("student_details2.csv", mode="r") as f:
  reader_file= csv_reader(f)
  #print(reader_data)

  for row in reader_file:
    if phone_number in row and password in row:
      print("login successful, ", row[0], "account has been found,with phone number", row[1])
      break
    else:
      pass
  else:
      print("login failed")

In [ ]:
print(" New Section")

CLASS WORK

In [ ]:
from csv import writer
phone_number= input("Enter your phone number: ")
password= input("Enter your password: ")
with open("classwork.csv", mode="r") as f:
  reader_file= csv_reader(f)


multiplication_table12= []
for i in range(1,12):

  multiplication_table12.append(1*6)
print(Multiplication_table12)

In [ ]:
classwork
+ generate a multiplication 1 to 12 and save it in a txt, csv file
+create sign in form

In [ ]:
with open("classwork.csv", mode="r") as f:
  reader_file= csv_reader(f)


multiplication_table12= []
for i in range(1,12):

  multiplication_table12.append(1*6)
print(Multiplication_table12)

In [ ]:
multiplication_table12= []
for i in range(1,12):

  multiplication_table12.append(1*6)
print(Multiplication_table12)


In [ ]:
with open("tables.txt", mode="w") as multiplication_table2:
  print(multiplication_table, file=multiplication_table2)

In [ ]:
from csv import writer
name= input("Enter your nDeame: ")
phone_number= input("Enter your phone number: ")
access_status= input("Enter your status: ")
password= input("Enter your password: ")
confirm_password= input("Confirm your password: ")

#save the above info
with open("student_details2.csv", mode="r") as f:
  reader_file= csv_reader(f)
  #print(reader_data)

  for row in reader_file:
    if phone_number in row and password in row:
      print("login successful, ", row[0], "account has been found,with phone number", row[1])
      break
    else:
      pass
  else:
      print("login failed")

In [ ]:
username= input("Enter your username: ")
password= input("Enter your password: ")
access_status= input('enter access_status')

#save the above info
details=[name,password,access_status]
with open("user_details4.csv", mode="w") as f:
  writer_data= writer(f)
  writer_data.writerow(details)

In [ ]:
usernamename= input("Enter your username: ")
password= input("Enter your password: ")

with open("users_details4.csv", mode='r') as f:
  reader_file = csv.reader(f)
  for row in reader_file:
    if username in row and password in row:
      print("Success", row[2], 'account accessed')
      break

  else:
    print("User not found")

PROJECT QUESTION: DEVELOP A CGPA CALCULATOR


In [ ]:
#VALIDATEERROR

FRIDAY,12, 2024


In [ ]:
print("******Welcome to CGPA calculator******")
print("")

student_name=input("Enter student_name: ")
student_matric_no=(int(input("Enter student_matric_no: ")))
student_level= (int(input("Enter student_level: ")))
student_semester=input("Enter student_semester: ")
student_section=input("Enter student_section: ")
Year_of_exam=input("Enter year_of_exam: ")


def cgpa_calculator():
  total_credit=0
  total_grade_point=0

  totalcoursesno="4"
  totalcoursesno=int(input("Enter number of courses you do: "))
  while totalcoursesno not in range(1,4):
    print("Enter course no under 4 numbers: ")
    totalcoursesno += 1
    break

  for i in range(0, totalcoursesno):

    course1 = input("Enter course name :  ")
    code=int(input("Enter course code: "))
    unit=int(input("Enter course unit:  "))
    score=int(input("Enter course score:  "))
    total_credit += unit* 5

  if (score >= 70):
        grade = 5
  elif (score < 70 and score >= 60):
    grade = 4
  elif (score < 60 and score >= 50):
    grade = 3
  elif (score < 50 and score >= 45):
    grade = 2
  elif (score < 45 and score >= 40):
    grade = 1
    grade= 1
  else:
    grade= 0
    obtainedGrade += unit*grade

  Cgpa =float((obtainedGrade / total_credit) * 5)
  print("THANKS FOR ALL YOUR INPUT YOUR CGPA IS : " + str(Cgpa))


cgpa_calculator()







In [ ]:
print("******Welcome to CGPA calculator******")
print("")

student_name=input("Enter student_name: ")
student_matric_no=(int(input("Enter student_matric_no: ")))
student_level= (int(input("Enter student_level: ")))
student_semester=input("Enter student_semester: ")
student_section=input("Enter student_section: ")
Year_of_exam=input("Enter year_of_exam: ")


def cgpa_calculator():
  total_credit=0
  obtainedGrade = 0 # Initialize obtainedGrade

  totalcoursesno="4"
  totalcoursesno=int(input("Enter number of courses you do: "))
  while totalcoursesno not in range(1,4):
    print("Enter course no under 4 numbers: ")
    totalcoursesno += 1
    break

  for i in range(0, totalcoursesno):

    course1 = input("Enter course name :  ")
    code=input("Enter course code: ") # Keep course code as a string
    unit=int(input("Enter course unit:  "))
    score=int(input("Enter course score:  "))
    total_credit += unit* 5

    if (score >= 70):
        grade = 5
    elif (score < 70 and score >= 60):
        grade = 4
    elif (score < 60 and score >= 50):
        grade = 3
    elif (score < 50 and score >= 45):
        grade = 2
    elif (score < 45 and score >= 40):
        grade = 1
        # grade= 1  # This line seems redundant
    else:
        grade= 0
    obtainedGrade += unit * grade # Calculate obtainedGrade within the loop

Cgpa = float((obtainedGrade / total_credit) * 5)
print("name: ", student_name,
      "matric no: ", student_matric_no,
      "CGPA: ", Cgpa)
cgpa_calculator()

In [ ]:
print("******Welcome to CGPA calculator******")
print("")

student_name = input("Enter student_name: ")
student_matric_no = int(input("Enter student_matric_no: "))
student_level = int(input("Enter student_level: "))
student_semester = input("Enter student_semester: ")
student_section = input("Enter student_section: ")
Year_of_exam = input("Enter year_of_exam: ")

def cgpa_calculator():
    total_credit = 0
    total_grade_point = 0

    # Initialize lists to store course data
    course_names = []
    course_codes = []
    course_units = []
    course_scores = []
    course_grades = []

    # Input for 4 courses
    for i in range(4):
        course_name = input(f"Enter course {i+1} name: ")
        code = input(f"Enter course {i+1} code: ")
        unit = int(input(f"Enter course {i+1} unit: "))
        score = int(input(f"Enter course {i+1} score: "))

        # Append data to lists
        course_names.append(course_name)
        course_codes.append(code)
        course_units.append(unit)
        course_scores.append(score)

        # Calculate grade and append
        if score >= 70:
            grade = 5
        elif score < 70 and score >= 60:
            grade = 4
        elif score < 60 and score >= 50:
            grade = 3
        elif score < 50 and score >= 45:
            grade = 2
        elif score < 45 and score >= 40:
            grade = 1
        else:
            grade = 0
        course_grades.append(grade)

        total_credit += unit * 5
        grade_point = unit * grade
        total_grade_point += grade_point

    cgpa = float((total_grade_point / total_credit) * 5)
    print("Name: ", student_name,
          "Matric No: ", student_matric_no,
          "CGPA: ", cgpa)

    # Option to add more courses
    while True:
        add_more = input("Do you want to add more courses? (yes/no): ")
        if add_more.lower() == 'yes':
            course_name = input("Enter course name: ")
            code = input("Enter course code: ")
            unit = int(input("Enter course unit: "))
            score = int(input("Enter course score: "))

            # Append data to lists
            course_names.append(course_name)
            course_codes.append(code)
            course_units.append(unit)
            course_scores.append(score)

            # Calculate grade and append
            if score >= 70:
                grade = 5
            elif score < 70 and score >= 60:
                grade = 4
            elif score < 60 and score >= 50:
                grade = 3
            elif score < 50 and score >= 45:
                grade = 2
            elif score < 45 and score >= 40:
                grade = 1
            else:
                grade = 0
            course_grades.append(grade)

            total_credit += unit * 5
            grade_point = unit * grade
            total_grade_point += grade_point

            # Recalculate CGPA
            cgpa = float((total_grade_point / total_credit) * 5)
            print("Updated CGPA: ", (round(cgpa,2)))

        else:
            break

cgpa_calculator()

In [ ]:
print("******Welcome to CGPA calculator******")
print("")

student_name = input("Enter student_name: ")
student_matric_no = input("Enter student_matric_no: ")
student_level = int(input("Enter student_level: "))
student_semester = input("Enter student_semester: ")
student_section = input("Enter student_section: ")
year_of_exam = input("Enter year_of_exam: ")

def cgpa_calculator():
    total_credit = 0
    total_grade_point = 0

    # Initialize lists to store course data
    course_names = []
    course_codes = []
    course_units = []
    course_scores = []
    course_grades = []

    # Input for 4 courses
    for i in range(4):
        course_name = input(f"Enter course {i+1} name: ")
        code = input(f"Enter course {i+1} code: ")
        unit = int(input(f"Enter course {i+1} unit: "))
        score = int(input(f"Enter course {i+1} score: "))

        # Append data to lists
        course_names.append(course_name)
        course_codes.append(code)
        course_units.append(unit)
        course_scores.append(score)

        # Calculate grade and append
        if score >= 70:
            grade = 'A'
            grade_point = 5
        elif score >= 60:
            grade = 'B'
            grade_point = 4
        elif score >= 50:
            grade = 'C'
            grade_point = 3
        elif score >= 45:
            grade = 'D'
            grade_point = 2
        elif score >= 40:
            grade = 'E'
            grade_point = 1
        else:
            grade = 'F'
            grade_point = 0
        course_grades.append(grade)

        total_credit += unit
        total_grade_point += unit * grade_point

    cgpa = total_grade_point / total_credit
    print("Name:", student_name,
          "Matric No:", student_matric_no,
          "CGPA:", round(cgpa, 2))

    # Option to add more courses
    while True:
        add_more = input("Do you want to add more courses? (yes/no): ")
        if add_more.lower() == 'yes':
            course_name = input("Enter course name: ")
            code = input("Enter course code: ")
            unit = int(input("Enter course unit: "))
            score = int(input("Enter course score: "))

            # Append data to lists
            course_names.append(course_name)
            course_codes.append(code)
            course_units.append(unit)
            course_scores.append(score)

            # Calculate grade and append
            if score >= 70:
                grade = 'A'
                grade_point = 5
            elif score >= 60:
                grade = 'B'
                grade_point = 4
            elif score >= 50:
                grade = 'C'
                grade_point = 3
            elif score >= 45:
                grade = 'D'
                grade_point = 2
            elif score >= 40:
                grade = 'E'
                grade_point = 1
            else:
                grade = 'F'
                grade_point = 0
            course_grades.append(grade)

            total_credit += unit
            total_grade_point += unit * grade_point

            # Recalculate CGPA
            cgpa = total_grade_point / total_credit
            print("Updated CGPA:", round(cgpa, 2))

        else:
            break

cgpa_calculator()


In [ ]:
print("******\n"
      "**      LAUTECH STUDENT CGPA CALCULATOR   **\n"
      "**   DEPARTMENT OF NUTRITION AND DIETETICS  **\n"
      "******\n")

student_name = input("Enter student name: ")
student_matric_no = int(input("Enter student matric number: "))
student_level = int(input("Enter student level: "))


while True:
    student_semester = input("Enter student semester (First semester/Second semester): ")
    if student_semester in ["First semester", "Second semester"]:
        break
    else:
        print("Invalid input. Please enter 'First semester' or 'Second semester'.")

#i want the user to enter anything other than either first semester or second semester,else print error
while True:
    student_session = input("Enter student section (Rain session/Harmattan session): ")
    if student_session in ["Rain session", "Harmattan session"]:
        break
    else:
        print("Invalid input. Please enter 'Rain session' or 'Harmattan session'.")

year_of_exam = int(input("Enter year of exam: "))

def cgpa_calculator():
    total_credit = 0
    total_grade_point = 0

    # these are the lists i needed to collect and store as data
    course_names = []
    course_codes = []
    course_units = []
    course_scores = []
    course_grades = []

    num_courses = int(input("Enter the number of courses: "))

    for i in range(num_courses):
        course_name = input(f"Enter course {i + 1} name: ")  # {i + 1} is to present a user-friendly numbering of courses, starting from 1 instead of 0
        code = input(f"Enter course {i + 1} code: ")
        unit = int(input(f"Enter course {i + 1} unit: "))
        score = int(input(f"Enter course {i + 1} score: "))

        # I'm Appending the data to the  lists here
        course_names.append(course_name)
        course_codes.append(code)
        course_units.append(unit)
        course_scores.append(score)

      #let grade

        if score >= 70:
            grade = 'A'
            grade_point = 5
        elif score >= 60:
            grade = 'B'
            grade_point = 4
        elif score >= 50:
            grade = 'C'
            grade_point = 3
        elif score >= 45:
            grade = 'D'
            grade_point = 2
        elif score >= 40:
            grade = 'E'
            grade_point = 1
        else:
            grade = 'F'
            grade_point = 0
        course_grades.append(grade)

        total_credit += unit
        total_grade_point += unit * grade_point

    cgpa = total_grade_point / total_credit

    if cgpa >= 4.5 and cgpa <= 5.0:
        class_ = "First Class"
    elif cgpa >= 3.5 and cgpa <= 4.49:
        class_ = "Second Class Upper"
    elif cgpa >= 2.5 and cgpa <= 3.49:
        class_ = "Second Class Lower"
    elif cgpa >= 1.5 and cgpa <= 2.49:
        class_ = "Third Class"
    elif cgpa >= 1.0 and cgpa <= 1.49:
        class_ = "Advise to Withdraw"
    else:
        class_ = "FAILED"

    print("\n****** STUDENT RESULT ******")
    print(f"Name: {student_name}")
    print(f"Matric No: {student_matric_no}")
    print(f"Level: {student_level}")
    print(f"Semester: {student_semester}")
    print(f"Section: {student_section}")
    print(f"Year of Exam: {year_of_exam}\n")

    print("Course Details:")
    print(f"{'Course Name':<20} {'Code':<10} {'Unit':<5} {'Score':<5} {'Grade':<5}")
    print("=" * 50)

    for i in range(num_courses):
        print(f"{course_names[i]:<20} {course_codes[i]:<10} {course_units[i]:<5} {course_scores[i]:<5} {course_grades[i]:<5}")

    print("=" * 50)
    print(f"Total Credits: {total_credit}")
    print(f"Total Grade Points: {total_grade_point}")
    print(f"CGPA: {round(cgpa, 2)}")
    print(f"Class: {class_}")
    print("****************************")

    # Option to add more courses
    while True:
        add_more = input("Do you want to add more courses? (yes/no): ")
        if add_more.lower() == 'yes':
            course_name = input("Enter course name: ")
            code = int(input("Enter course code: "))
            unit = int(input("Enter course unit: "))
            score = int(input("Enter course score: "))

            # let me append list to avoid overwritten
            course_names.append(course_name)
            course_codes.append(code)
            course_units.append(unit)
            course_scores.append(score)

            if score >= 70:
                grade = 'A'
                grade_point = 5
            elif score >= 60:
                grade = 'B'
                grade_point = 4
            elif score >= 50:
                grade = 'C'
                grade_point = 3
            elif score >= 45:
                grade = 'D'
                grade_point = 2
            elif score >= 40:
                grade = 'E'
                grade_point = 1
            else:
                grade = 'F'
                grade_point = 0
            course_grades.append(grade)

            total_credit += unit
            total_grade_point += unit * grade_point


            cgpa = total_grade_point / total_credit

            if cgpa >= 4.5 and cgpa <= 5.0:
                class_ = "First Class"
            elif cgpa >= 3.5 and cgpa <= 4.49:
                class_ = "Second Class Upper"
            elif cgpa >= 2.5 and cgpa <= 3.49:
                class_ = "Second Class Lower"
            elif cgpa >= 1.5 and cgpa <= 2.49:
                class_ = "Third Class"
            elif cgpa >= 1.0 and cgpa <= 1.49:
                class_ = "Advise to Withdraw"
            else:
                class_ = "FAILED"

            print("\n****** UPDATED STUDENT RESULT ******")
            print(f"Updated CGPA: {round(cgpa, 2)}")
            print(f"Class: {class_}")
            print("****************************")

        else:
            break

cgpa_calculator()


In [ ]:
print("******\n"
      "**      LAUTECH STUDENT CGPA CALCULATOR   **\n"
      "**   DEPARTMENT OF NUTRITION AND DIETETICS  **\n"
      "******\n")

student_name = input("Enter student name: ")

# Validate matric number (must be exactly 6 digits)
while True:
    student_matric_no = input("Enter student matric number (6 digits): ")
    if student_matric_no.isdigit() and len(student_matric_no) == 6:
        student_matric_no = int(student_matric_no)
        break
    else:
        print("Invalid input. Matric number must be exactly 6 digits.")

# Validate student level (must be between 100 and 500)
while True:
    student_level = input("Enter student level (100-500): ")
    if student_level.isdigit() and 100 <= int(student_level) <= 500:
        student_level = int(student_level)
        break
    else:
        print("Invalid input. Level must be a digit between 100 and 500.")

# Validate semester input (case-insensitive)
while True:
    student_semester = input("Enter student semester (First semester/Second semester): ").lower()
    if student_semester in ["first semester", "second semester"]:
        break
    else:
        print("Invalid input. Please enter 'First semester' or 'Second semester'.")

# Validate session input (case-insensitive)
while True:
    student_session = input("Enter student session (Rain session/Harmattan session): ").lower()
    if student_session in ["rain session", "harmattan session"]:
        break
    else:
        print("Invalid input. Please enter 'Rain session' or 'Harmattan session'.")

# Validate year of exam (must be a digit)
while True:
    year_of_exam = input("Enter year of exam: ")
    if year_of_exam.isdigit():
        year_of_exam = int(year_of_exam)
        break
    else:
        print("Invalid input. Year of exam must be a digit.")

# CGPA calculator for both semesters
def cgpa_calculator(semester):
    print(f"\n** Calculating CGPA for {semester} **\n")
    total_credit = 0
    total_grade_point = 0

    # these are the lists to collect and store as data
    course_names = []
    course_codes = []
    course_units = []
    course_scores = []
    course_grades = []

    num_courses = int(input(f"Enter the number of courses for {semester}: "))

    for i in range(num_courses):
        course_name = input(f"Enter course {i + 1} name: ")
        code = input(f"Enter course {i + 1} code: ")
        unit = int(input(f"Enter course {i + 1} unit: "))
        score = int(input(f"Enter course {i + 1} score: "))

        # Append data to the lists
        course_names.append(course_name)
        course_codes.append(code)
        course_units.append(unit)
        course_scores.append(score)

        # Assign grades and grade points
        if score >= 70:
            grade = 'A'
            grade_point = 5
        elif score >= 60:
            grade = 'B'
            grade_point = 4
        elif score >= 50:
            grade = 'C'
            grade_point = 3
        elif score >= 45:
            grade = 'D'
            grade_point = 2
        elif score >= 40:
            grade = 'E'
            grade_point = 1
        else:
            grade = 'F'
            grade_point = 0
        course_grades.append(grade)

        total_credit += unit
        total_grade_point += unit * grade_point

    cgpa = total_grade_point / total_credit

    # Determine class
    if cgpa >= 4.5 and cgpa <= 5.0:
        class_ = "First Class"
    elif cgpa >= 3.5 and cgpa <= 4.49:
        class_ = "Second Class Upper"
    elif cgpa >= 2.5 and cgpa <= 3.49:
        class_ = "Second Class Lower"
    elif cgpa >= 1.5 and cgpa <= 2.49:
        class_ = "Third Class"
    elif cgpa >= 1.0 and cgpa <= 1.49:
        class_ = "Advise to Withdraw"
    else:
        class_ = "FAILED"

    # Print results
    print("\n****** STUDENT RESULT ******")
    print(f"Name: {student_name}")
    print(f"Matric No: {student_matric_no}")
    print(f"Level: {student_level}")
    print(f"Semester: {semester}")
    print(f"Session: {student_session}")
    print(f"Year of Exam: {year_of_exam}\n")

    print("Course Details:")
    print(f"{'Course Name':<20} {'Code':<10} {'Unit':<5} {'Score':<5} {'Grade':<5}")
    print("=" * 50)

    for i in range(num_courses):
        print(f"{course_names[i]:<20} {course_codes[i]:<10} {course_units[i]:<5} {course_scores[i]:<5} {course_grades[i]:<5}")

    print("=" * 50)
    print(f"Total Credits: {total_credit}")
    print(f"Total Grade Points: {total_grade_point}")
    print(f"CGPA: {round(cgpa, 2)}")
    print(f"Class: {class_}")
    print("****************************")

    return cgpa, total_credit

# Calculate for both semesters
first_semester_cgpa, first_semester_credits = cgpa_calculator("First Semester")
second_semester_cgpa, second_semester_credits = cgpa_calculator("Second Semester")

# Calculate the overall CGPA
total_credits = first_semester_credits + second_semester_credits
overall_cgpa = (first_semester_cgpa * first_semester_credits + second_semester_cgpa * second_semester_credits) / total_credits

print("\n****** OVERALL CGPA ******")
print(f"Overall CGPA: {round(overall_cgpa, 2)}")
print("****************************")


******
**      LAUTECH STUDENT CGPA CALCULATOR   **
**   DEPARTMENT OF NUTRITION AND DIETETICS  **
******

Enter student name: desmond
Enter student matric number (6 digits): 222
Invalid input. Matric number must be exactly 6 digits.
Enter student matric number (6 digits): 195275
Enter student level (100-500): 200
Enter student semester (First semester/Second semester): first semester
Enter student session (Rain session/Harmattan session): rain
Invalid input. Please enter 'Rain session' or 'Harmattan session'.
Enter student session (Rain session/Harmattan session): rain session
Enter year of exam: 2004

** Calculating CGPA for First Semester **

Enter the number of courses for First Semester: 2
Enter course 1 name: mth
Enter course 1 code: 202
Enter course 1 unit: 4
Enter course 1 score: 69
Enter course 2 name: gns
Enter course 2 code: 202
Enter course 2 unit: 4
Enter course 2 score: 53

****** STUDENT RESULT ******
Name: desmond
Matric No: 195275
Level: 200
Semester: First Semester
Se

# New section

In [13]:
print("******\n"
      "**      LAUTECH STUDENT CGPA CALCULATOR   **\n"
      "**   DEPARTMENT OF NUTRITION AND DIETETICS  **\n"
      "******\n")

student_name = input("Enter student name: ")

# Validate matric number (must be exactly 6 digits)
while True:
    student_matric_no = input("Enter student matric number (6 digits): ")
    if student_matric_no.isdigit() and len(student_matric_no) == 6:
        student_matric_no = int(student_matric_no)
        break
    else:
        print("Invalid input. Matric number must be exactly 6 digits.")

# Validate gender (male/female)
while True:
    student_gender = input("Enter gender (Male/Female): ").lower()
    if student_gender in ["male", "female"]:
        break
    else:
        print("Invalid input. Gender must be 'Male' or 'Female'.")

# Validate student level (must be between 100 and 500)
while True:
    student_level = input("Enter student level (100-500): ")
    if student_level.isdigit() and 100 <= int(student_level) <= 500:
        student_level = int(student_level)
        break
    else:
        print("Invalid input. Level must be a digit between 100 and 500.")

# Validate semester input (case-insensitive)
while True:
    student_semester = input("Enter student semester (First semester/Second semester): ").lower()
    if student_semester in ["first semester", "second semester"]:
        break
    else:
        print("Invalid input. Please enter 'First semester' or 'Second semester'.")

# Validate session input (case-insensitive)
while True:
    student_session = input("Enter student session (Rain session/Harmattan session): ").lower()
    if student_session in ["rain session", "harmattan session"]:
        break
    else:
        print("Invalid input. Please enter 'Rain session' or 'Harmattan session'.")

# Validate year of exam (must be a digit)
while True:
    year_of_exam = input("Enter year of exam: ")
    if year_of_exam.isdigit():
        year_of_exam = int(year_of_exam)
        break
    else:
        print("Invalid input. Year of exam must be a digit.")

# CGPA calculator for both semesters
def cgpa_calculator(semester):
    print(f"\n** Calculating CGPA for {semester} **\n")
    total_credit = 0
    total_grade_point = 0

    # these are the lists to collect and store as data
    course_names = []
    course_codes = []
    course_units = []
    course_scores = []
    course_grades = []

    num_courses = int(input(f"Enter the number of courses for {semester}: "))

    for i in range(num_courses):
        course_name = input(f"Enter course {i + 1} name: ")
        code = input(f"Enter course {i + 1} code: ")
        unit = int(input(f"Enter course {i + 1} unit: "))
        score = int(input(f"Enter course {i + 1} score: "))

        # Append data to the lists
        course_names.append(course_name)
        course_codes.append(code)
        course_units.append(unit)
        course_scores.append(score)

        # Assign grades and grade points
        if score >= 70:
            grade = 'A'
            grade_point = 5
        elif score >= 60:
            grade = 'B'
            grade_point = 4
        elif score >= 50:
            grade = 'C'
            grade_point = 3
        elif score >= 45:
            grade = 'D'
            grade_point = 2
        elif score >= 40:
            grade = 'E'
            grade_point = 1
        else:
            grade = 'F'
            grade_point = 0
        course_grades.append(grade)

        total_credit += unit
        total_grade_point += unit * grade_point

    gpa = total_grade_point / total_credit

    # Determine class
    if gpa >= 4.5 and gpa <= 5.0:
        class_ = "First Class"
    elif gpa >= 3.5 and gpa <= 4.49:
        class_ = "Second Class Upper"
    elif gpa >= 2.5 and gpa <= 3.49:
        class_ = "Second Class Lower"
    elif gpa >= 1.5 and gpa <= 2.49:
        class_ = "Third Class"
    elif gpa >= 1.0 and gpa <= 1.49:
        class_ = "Advise to Withdraw"
    else:
        class_ = "FAILED"

    # Print results with design formatting
    print(f'''
    __________________________________________________________________________________________________
    |MATRIC NO: {student_matric_no}   |STUDENT NAME: {student_name.upper()}   |BATCH: A    |GPR: A|
    ---------------------------------------------------------------------------------------------------
    |GENDER: {student_gender.upper()}   |SEMESTER: {semester.upper()}   |PROGRAM: B.TECH   |DEPT: NUTRITION   |LEVEL: {student_level}
    ---------------------------------------------------------------------------------------------------
    |REMARK: CLEARED|
    ---------------------------------------------------------------------------------------------------
    ''')

    print(f'''
    ---------------------------------------------------------------------------------------------------
                               {student_level} LEVEL {semester.upper()} SEMESTER
    ---------------------------------------------------------------------------------------------------
    S/N    COURSE CODE                 COURSE TITLE                       UNIT      SCORE    GRADE    POINT
    ---------------------------------------------------------------------------------------------------''')

    for i in range(num_courses):
        print(f"{i + 1:<7}{course_codes[i]:<25}{course_names[i]:<30}{course_units[i]:<10}{course_scores[i]:<10}{course_grades[i]:<10}")

    print(f'''
    ---------------------------------------------------------------------------------------------------
                                    {semester.upper()} SEMESTER PERFORMANCE
    ---------------------------------------------------------------------------------------------------
    POINT               UNIT           GPA        CLASS
    ---------------------------------------------------------------------------------------------------
    {total_grade_point}   {total_credit}     {gpa:.2f}    {class_}
    ---------------------------------------------------------------------------------------------------
    ''')

    return gpa, total_credit

# Calculate for both semesters
first_semester_gpa, first_semester_credits = cgpa_calculator("First Semester")
second_semester_gpa, second_semester_credits = cgpa_calculator("Second Semester")

# Calculate the overall CGPA
total_credits = first_semester_credits + second_semester_credits
overall_cgpa = (first_semester_gpa * first_semester_credits + second_semester_gpa * second_semester_credits) / total_credits

# Print overall CGPA with design formatting
print(f'''
---------------------------------------------------------------------------------------------------
                                    OVERALL CGPA PERFORMANCE
---------------------------------------------------------------------------------------------------
POINT               UNIT           GPA        CLASS
---------------------------------------------------------------------------------------------------
{first_semester_gpa * first_semester_credits + second_semester_gpa * second_semester_credits:.2f}    {total_credits}    {overall_cgpa:.2f}    {class_}
---------------------------------------------------------------------------------------------------
''')


******
**      LAUTECH STUDENT CGPA CALCULATOR   **
**   DEPARTMENT OF NUTRITION AND DIETETICS  **
******



KeyboardInterrupt: Interrupted by user

In [17]:
print("******\n"
      "**      LAUTECH STUDENT CGPA CALCULATOR   **\n"
      "**   DEPARTMENT OF NUTRITION AND DIETETICS  **\n"
      "******\n")

student_name = input("Enter student name: ")

# Validate gender input (must be male or female)
while True:
    student_gender = input("Enter gender (Male/Female): ").lower()
    if student_gender in ["male", "female"]:
        student_gender = student_gender.capitalize()
        break
    else:
        print("Invalid input. Please enter 'Male' or 'Female'.")

# Validate matric number (must be exactly 6 digits)
while True:
    student_matric_no = input("Enter student matric number (6 digits): ")
    if student_matric_no.isdigit() and len(student_matric_no) == 6:
        student_matric_no = int(student_matric_no)
        break
    else:
        print("Invalid input. Matric number must be exactly 6 digits.")

# Validate student level (must be between 100 and 500)
while True:
    student_level = input("Enter student level (100-500): ")
    if student_level.isdigit() and 100 <= int(student_level) <= 500:
        student_level = int(student_level)
        break
    else:
        print("Invalid input. Level must be a digit between 100 and 500.")

# Validate semester input (case-insensitive)
while True:
    student_semester = input("Enter student semester (First semester/Second semester): ").lower()
    if student_semester in ["first semester", "second semester"]:
        break
    else:
        print("Invalid input. Please enter 'First semester' or 'Second semester'.")

# Validate session input (case-insensitive)
while True:
    student_session = input("Enter student session (Rain session/Harmattan session): ").lower()
    if student_session in ["rain session", "harmattan session"]:
        break
    else:
        print("Invalid input. Please enter 'Rain session' or 'Harmattan session'.")

# Validate year of exam (must be a digit)
while True:
    year_of_exam = input("Enter year of exam: ")
    if year_of_exam.isdigit():
        year_of_exam = int(year_of_exam)
        break
    else:
        print("Invalid input. Year of exam must be a digit.")

# CGPA calculator for both semesters
def cgpa_calculator(semester):
    print(f"\n** Calculating CGPA for {semester} **\n")
    total_credit = 0
    total_grade_point = 0

    # these are the lists to collect and store as data
    course_names = []
    course_codes = []
    course_units = []
    course_scores = []
    course_grades = []

    num_courses = int(input(f"Enter the number of courses for {semester}: "))

    for i in range(num_courses):
        course_name = input(f"Enter course {i + 1} name: ")
        code = input(f"Enter course {i + 1} code: ")
        unit = int(input(f"Enter course {i + 1} unit: "))
        score = int(input(f"Enter course {i + 1} score: "))

        # Append data to the lists
        course_names.append(course_name)
        course_codes.append(code)
        course_units.append(unit)
        course_scores.append(score)

        # Assign grades and grade points
        if score >= 70:
            grade = 'A'
            grade_point = 5
        elif score >= 60:
            grade = 'B'
            grade_point = 4
        elif score >= 50:
            grade = 'C'
            grade_point = 3
        elif score >= 45:
            grade = 'D'
            grade_point = 2
        elif score >= 40:
            grade = 'E'
            grade_point = 1
        else:
            grade = 'F'
            grade_point = 0
        course_grades.append(grade)

        total_credit += unit
        total_grade_point += unit * grade_point

    cgpa = total_grade_point / total_credit

    # Determine class
    if cgpa >= 4.5 and cgpa <= 5.0:
        class_ = "First Class"
    elif cgpa >= 3.5 and cgpa <= 4.49:
        class_ = "Second Class Upper"
    elif cgpa >= 2.5 and cgpa <= 3.49:
        class_ = "Second Class Lower"
    elif cgpa >= 1.5 and cgpa <= 2.49:
        class_ = "Third Class"
    elif cgpa >= 1.0 and cgpa <= 1.49:
        class_ = "Advise to Withdraw"
    else:
        class_ = "FAILED"

    # Print formatted results
    print(f'''
__________________________________________________________________________________________________
|MATRIC NO: {student_matric_no:<12} | STUDENT NAME: {student_name.upper():<20} | BATCH: A | GPR: A |
---------------------------------------------------------------------------------------------------
|GENDER: {student_gender:<10} | SEMESTER: {semester.upper():<15} | PROGRAM: B.TECH | DEPT: {'NUTRITION AND DIETETICS':<20} | LEVEL: {student_level}
---------------------------------------------------------------------------------------------------
|REMARK: CLEARED |
---------------------------------------------------------------------------------------------------''')

    print(f'''
---------------------------------------------------------------------------------------------------
                               {student_level} LEVEL {semester.upper()} SEMESTER
---------------------------------------------------------------------------------------------------
S/N    COURSE CODE                 COURSE TITLE                       UNIT      SCORE    GRADE    POINT
---------------------------------------------------------------------------------------------------''')

    for i in range(num_courses):
        # Align all values using string formatting
        print(f'{i + 1:<6} {course_codes[i]:<27} {course_names[i]:<35} {course_units[i]:<9} {course_scores[i]:<9} {course_grades[i]:<8} {course_units[i] * (5 if course_grades[i] == "A" else 4 if course_grades[i] == "B" else 3 if course_grades[i] == "C" else 2 if course_grades[i] == "D" else 1 if course_grades[i] == "E" else 0):<5}')

    print(f'''
---------------------------------------------------------------------------------------------------
                                    {semester.upper()} SEMESTER PERFORMANCE
---------------------------------------------------------------------------------------------------
POINT               UNIT           GPA        CLASS              POINT              UNIT         CGPA     CLASS
---------------------------------------------------------------------------------------------------''')

    print(f'{total_grade_point:<19} {total_credit:<14} {round(cgpa, 2):<11} {class_:<17} {total_grade_point:<19} {total_credit:<13} {round(cgpa, 2):<9} {class_:<10}')
    print("---------------------------------------------------------------------------------------------------")

    return cgpa, total_credit

# Calculate for both semesters
first_semester_cgpa, first_semester_credits = cgpa_calculator("First Semester")
second_semester_cgpa, second_semester_credits = cgpa_calculator("Second Semester")

# Calculate the overall CGPA
total_credits = first_semester_credits + second_semester_credits
overall_cgpa = (first_semester_cgpa * first_semester_credits + second_semester_cgpa * second_semester_credits) / total_credits

print("\n****** OVERALL CGPA ******")
print(f"Overall CGPA: {round(overall_cgpa, 2)}")
print("****************************")


******
**      LAUTECH STUDENT CGPA CALCULATOR   **
**   DEPARTMENT OF NUTRITION AND DIETETICS  **
******

Enter student name: desmond
Enter gender (Male/Female): male
Enter student matric number (6 digits): 195345
Enter student level (100-500): 400
Enter student semester (First semester/Second semester): first semester
Enter student session (Rain session/Harmattan session): rain session
Enter year of exam: 2002

** Calculating CGPA for First Semester **

Enter the number of courses for First Semester: 1
Enter course 1 name: nud
Enter course 1 code: 402
Enter course 1 unit: 3
Enter course 1 score: 70

__________________________________________________________________________________________________
|MATRIC NO: 195345       | STUDENT NAME: DESMOND              | BATCH: A | GPR: A |
---------------------------------------------------------------------------------------------------
|GENDER: Male       | SEMESTER: FIRST SEMESTER  | PROGRAM: B.TECH | DEPT: NUTRITION AND DIETETICS | LEVEL: 4

In [ ]:
print("Helo")551


In [ ]:
import random
import datetime

# Global List Declaration
name = []
phno = []
add = []
checkin = []
checkout = []
room = []
price = []
rc = []
p = []
roomno = []
custid = []
day = []

# Global Variable Declaration
i = 0

# Home Function
def Home():
    print("\t\t\t\t\t\t WELCOME TO HOTEL ANCASA\n")
    print("\t\t\t 1 Booking\n")
    print("\t\t\t 2 Rooms Info\n")
    print("\t\t\t 3 Room Service(Menu Card)\n")
    print("\t\t\t 4 Payment\n")
    print("\t\t\t 5 Record\n")
    print("\t\t\t 0 Exit\n")

    ch = int(input("-> "))

    if ch == 1:
        Booking()
    elif ch == 2:
        Rooms_Info()
    elif ch == 3:
        restaurant()
    elif ch == 4:
        Payment()
    elif ch == 5:
        Record()
    else:
        exit()

# Function used in booking
def date(c):
    if c[2] >= 2019 and c[2] <= 2020:
        if c[1] != 0 and c[1] <= 12:
            if c[1] == 2 and c[0] != 0 and c[0] <= 31:
                if c[2] % 4 == 0 and c[0] <= 29:
                    pass
                elif c[0] < 29:
                    pass
                else:
                    print("Invalid date\n")
                    reset_booking_data()
                    Booking()
            elif c[1] <= 7 and c[1] % 2 != 0 and c[0] <= 31:
                pass
            elif c[1] <= 7 and c[1] % 2 == 0 and c[0] <= 30 and c[1] != 2:
                pass
            elif c[1] >= 8 and c[1] % 2 == 0 and c[0] <= 31:
                pass
            elif c[1] >= 8 and c[1] % 2 != 0 and c[0] <= 30:
                pass
            else:
                print("Invalid date\n")
                reset_booking_data()
                Booking()
        else:
            print("Invalid date\n")
            reset_booking_data()
            Booking()
    else:
        print("Invalid date\n")
        reset_booking_data()
        Booking()

def reset_booking_data():
    global i
    name.pop(i)
    phno.pop(i)
    add.pop(i)
    checkin.pop(i)
    checkout.pop(i)

# Booking function
def Booking():
    global i
    print(" BOOKING ROOMS\n")

    while True:
        n = input("Name: ").strip()
        p1 = input("Phone No.: ").strip()
        a = input("Address: ").strip()

        if n and p1 and a:
            name.append(n)
            phno.append(p1)
            add.append(a)
            break
        else:
            print("\tName, Phone no. & Address cannot be empty..!!")

    cii = input("Check-In (dd/mm/yyyy): ").strip()
    checkin.append(cii)
    ci = list(map(int, cii.split('/')))
    date(ci)

    coo = input("Check-Out (dd/mm/yyyy): ").strip()
    checkout.append(coo)
    co = list(map(int, coo.split('/')))

    if (co[2], co[1], co[0]) <= (ci[2], ci[1], ci[0]):
        print("\n\tErr..!!\n\tCheck-Out date must fall after Check-In\n")
        reset_booking_data()
        Booking()
    else:
        date(co)

    d1 = datetime.datetime(ci[2], ci[1], ci[0])
    d2 = datetime.datetime(co[2], co[1], co[0])
    d = (d2 - d1).days
    day.append(d)

    print("----SELECT ROOM TYPE----")
    print(" 1. Standard Non-AC")
    print(" 2. Standard AC")
    print(" 3. 3-Bed Non-AC")
    print(" 4. 3-Bed AC")
    print("\t\tPress 0 for Room Prices")

    ch = int(input("-> "))

    if ch == 0:
        print(" 1. Standard Non-AC - Rs. 3500")
        print(" 2. Standard AC - Rs. 4000")
        print(" 3. 3-Bed Non-AC - Rs. 4500")
        print(" 4. 3-Bed AC - Rs. 5000")
        ch = int(input("-> "))

    room_types = {
        1: ("Standard Non-AC", 3500),
        2: ("Standard AC", 4000),
        3: ("3-Bed Non-AC", 4500),
        4: ("3-Bed AC", 5000)
    }

    if ch in room_types:
        room_type, room_price = room_types[ch]
        room.append(room_type)
        price.append(room_price)
        print(f"Room Type- {room_type}")
        print(f"Price- {room_price}")
    else:
        print("Wrong choice..!!")
        return

    rn = random.randint(300, 339)
    cid = random.randint(10, 49)

    while rn in roomno or cid in custid:
        rn = random.randint(300, 339)
        cid = random.randint(10, 49)

    rc.append(0)
    p.append(0)

    print("")
    print("\t\t\t***ROOM BOOKED SUCCESSFULLY***\n")
    print(f"Room No. - {rn}")
    print(f"Customer Id - {cid}")
    roomno.append(rn)
    custid.append(cid)
    i += 1

    if int(input("0-BACK\n -> ")) == 0:
        Home()
    else:
        exit()

# ROOMS INFO
def Rooms_Info():
    print("		 ------ HOTEL ROOMS INFO ------\n")
    room_info = [
        ("STANDARD NON-AC", [
            "1 Double Bed, Television, Telephone,",
            "Double-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and",
            "an attached washroom with hot/cold water."
        ]),
        ("STANDARD AC", [
            "1 Double Bed, Television, Telephone,",
            "Double-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and",
            "an attached washroom with hot/cold water + Window/Split AC."
        ]),
        ("3-Bed NON-AC", [
            "1 Double Bed + 1 Single Bed, Television,",
            "Telephone, a Triple-Door Cupboard, 1 Coffee table with 2 sofa, 1",
            "Side table, Balcony with an Accent table with 2 Chair and an",
            "attached washroom with hot/cold water."
        ]),
        ("3-Bed AC", [
            "1 Double Bed + 1 Single Bed, Television,",
            "Telephone, a Triple-Door Cupboard, 1 Coffee table with 2 sofa,",
            "1 Side table, Balcony with an Accent table with 2 Chair and an",
            "attached washroom with hot/cold water + Window/Split AC."
        ]),
    ]

    for room_type, amenities in room_info:
        print(f"{room_type}")
        print("---------------------------------------------------------------")
        for amenity in amenities:
            print(amenity)
        print("\n")

    if int(input("0-BACK\n -> ")) == 0:
        Home()
    else:
        exit()

# RESTAURANT FUNCTION
def restaurant():
    ph = int(input("Customer Id: "))
    global i
    f = 0
    r = 0

    for n in range(i):
        if custid[n] == ph and p[n] == 0:
            f = 1
            print("-------------------------------------------------------------------------")
            print("						 Hotel AnCasa")
            print("-------------------------------------------------------------------------")
            print("						 Menu Card")
            print("-------------------------------------------------------------------------")
            print("\n BEVERAGES                            26 Dal Fry................ 140.00")
            print("----------------------------------    27 Dal Makhani............ 150.00")
            print(" 1 Regular Tea............. 20.00    28 Dal Tadka.............. 150.00")
            print(" 2 Masala Tea.............. 25.00")
            print(" 3 Coffee.................. 25.00    ROTI")
            print(" 4 Cold Drink.............. 25.00    ----------------------------------")
            print(" 5 Bread Butter............ 30.00    29 Plain Roti.............. 15.00")
            print(" 6 Bread Jam............... 30.00    30 Butter Roti............. 15.00")
            print(" 7 Veg. Sandwich........... 50.00    31 Tandoori Roti........... 20.00")
            print(" 8 Veg. Toast Sandwich..... 50.00    32 Butter Naan............. 20.00")
            print(" 9 Cheese Toast Sandwich... 70.00")
            print(" 10 Grilled Sandwich........ 70.00    RICE")
            print("                                      ----------------------------------")
            print(" SOUPS                                 33 Plain Rice............. 90.00")
            print("----------------------------------    34 Jeera Rice............. 90.00")
            print(" 11 Tomato Soup............ 110.00    35 Veg Pulao.............. 110.00")
            print(" 12 Hot & Sour............. 110.00    36 Peas Pulao............. 110.00")
            print(" 13 Veg. Noodle Soup....... 110.00")
            print(" 14 Sweet Corn............. 110.00    SOUTH INDIAN")
            print(" 15 Veg. Munchow........... 110.00    ----------------------------------")
            print("                                      37 Plain Dosa............. 100.00")
            print(" MAIN COURSE                           38 Onion Dosa............. 110.00")
            print("----------------------------------    39 Masala Dosa............ 130.00")
            print(" 16 Shahi Paneer........... 110.00    40 Paneer Dosa............ 130.00")
            print(" 17 Kadai Paneer........... 110.00    41 Rice Idli.............. 130.00")
            print(" 18 Handi Paneer........... 120.00    42 Sambhar Vada........... 140.00")
            print(" 19 Palak Paneer........... 120.00")
            print(" 20 Chilli Paneer.......... 140.00    ICE CREAM")
            print(" 21 Matar Mushroom......... 140.00    ----------------------------------")
            print(" 22 Mix Veg................ 140.00    43 Vanilla................. 60.00")
            print(" 23 Jeera Aloo............. 140.00    44 Strawberry.............. 60.00")
            print(" 24 Malai Kofta............ 140.00    45 Pineapple............... 60.00")
            print(" 25 Aloo Matar............. 140.00    46 Butter Scotch........... 60.00")
            print("                                      47 Chocolate............... 60.00")
            print("-------------------------------------------------------------------------")
            print("\n 48 -2 Times \t 49-3 Times \t 50-Exit")
            ch = int(input("->"))

            if ch == 50:
                exit()
            elif ch in (48, 49):
                f = ch
                break

    if f == 48:
        rc.append(2)
        p.append(2)
        print("\n Charges added successfully\n")

    elif f == 49:
        rc.append(3)
        p.append(3)
        print("\n Charges added successfully\n")

    elif r == 0:
        print("\n Invalid Customer Id\n")
        restaurant()

    if int(input("0-BACK\n -> ")) == 0:
        Home()
    else:
        exit()

# PAYMENT FUNCTION
def Payment():
    ph = int(input("Customer Id: "))
    global i
    f = 0
    r = 0

    for n in range(i):
        if custid[n] == ph and p[n] == 0:
            f = 1
            print("-------------------------------------------------------------------------")
            print("					 Hotel AnCasa")
            print("-------------------------------------------------------------------------")
            print("						 BILL")
            print("-------------------------------------------------------------------------")
            print(f" Customer Id: {custid[n]}\t\t\t\t Room No: {roomno[n]}")
            print(f" Customer Name: {name[n]}\t\t\t Phone No: {phno[n]}")
            print(f" Address: {add[n]}")
            print(f" Check-In: {checkin[n]}\t\t\t Check-Out: {checkout[n]}")
            print("\n-------------------------------------------------------------------------")
            print(" Room Type: " + room[n])
            print(" Room Charges: " + str(price[n] * day[n]) + "/-")
            if rc[n] != 0:
                print(" Restaurant Charges: " + str(rc[n] * 1000) + "/-")
            print("-------------------------------------------------------------------------")
            print(" Total Amount: " + str(price[n] * day[n] + rc[n] * 1000) + "/-")
            print("-------------------------------------------------------------------------")
            print("Thank You. Visit Again :)")
            print("-------------------------------------------------------------------------")
            p.pop(n)
            p.insert(n, 1)
            roomno.pop(n)
            custid.pop(n)
            break

    if f == 0:
        print("\n Invalid Customer Id\n")
        Payment()

    if int(input("0-BACK\n -> ")) == 0:
        Home()
    else:
        exit()

# RECORD FUNCTION
def Record():
    ph = int(input("Customer Id: "))
    global i
    f = 0

    for n in range(i):
        if custid[n] == ph:
            f = 1
            print("-------------------------------------------------------------------------")
            print("					 Hotel AnCasa")
            print("-------------------------------------------------------------------------")
            print("						 RECORD")
            print("-------------------------------------------------------------------------")
            print(f" Customer Id: {custid[n]}\t\t\t\t Room No: {roomno[n]}")
            print(f" Customer Name: {name[n]}\t\t\t Phone No: {phno[n]}")
            print(f" Address: {add[n]}")
            print(f" Check-In: {checkin[n]}\t\t\t Check-Out: {checkout[n]}")
            print("\n-------------------------------------------------------------------------")
            print(" Room Type: " + room[n])
            print(" Room Charges: " + str(price[n] * day[n]) + "/-")
            if rc[n] != 0:
                print(" Restaurant Charges: " + str(rc[n] * 1000) + "/-")
            print("-------------------------------------------------------------------------")
            print(" Total Amount: " + str(price[n] * day[n] + rc[n] * 1000) + "/-")
            print("-------------------------------------------------------------------------")
            print("Thank You. Visit Again :)")
            print("-------------------------------------------------------------------------")
            break

    if f == 0:
        print("\n Invalid Customer Id\n")
        Record()

    if int(input("0-BACK\n -> ")) == 0:
        Home()
    else:
        exit()

Home()


						 WELCOME TO HOTEL ANCASA

			 1 Booking

			 2 Rooms Info

			 3 Room Service(Menu Card)

			 4 Payment

			 5 Record

			 0 Exit



KeyboardInterrupt: Interrupted by user

In [19]:
from google.colab import drive
drive.mount('/content/gdrive')

%cd /content/gdrive/MyDrive/Colab Notebooks

!download my_code.py --dst /Users/username/Downloads

!zip my_directory.zip my_directory
!download my_directory.zip


Mounted at /content/gdrive
/content/gdrive/MyDrive/Colab Notebooks
/bin/bash: line 1: download: command not found
	zip warning: name not matched: my_directory

zip error: Nothing to do! (my_directory.zip)
/bin/bash: line 1: download: command not found
